### ISSUE TITLE
Reporte de practica

### ISSUE THREAD

**Issue by garaudy12** [SistemasTecTlaxiaco/practicaprototipos-dream-team#3]
[Reporte De La Practica (2).pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-dream-team/files/6190864/Reporte.De.La.Practica.2.pdf)

**Comment by josealfredo79** [comment]
Deben describir los trabajos mas detalladamente, por favor.

**Comment by josealfredo79** [comment]
La calificación debe ir en este apartado.
